/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as RegisterEventIdRouteImport } from './routes/register.$eventId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEventIdRoute = RegisterEventIdRouteImport.update({
  id: '/register/$eventId',
  path: '/register/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof ProfileRoute
  '/registrations': typeof RegistrationsRoute
  '/saved': typeof SavedRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof ProfileRoute
  '/registrations': typeof RegistrationsRoute
  '/saved': typeof SavedRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/profile': typeof ProfileRoute
  '/registrations': typeof RegistrationsRoute
  '/saved': typeof SavedRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/registrations'
    | '/saved'
    | '/events/$eventId'
    | '/register/$eventId'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/registrations'
    | '/saved'
    | '/events/$eventId'
    | '/register/$eventId'
    | '/events'
  id:
    | '__root__'
    | '/profile'
    | '/registrations'
    | '/saved'
    | '/events/$eventId'
    | '/register/$eventId'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProfileRoute: typeof ProfileRoute
  RegistrationsRoute: typeof RegistrationsRoute
  SavedRoute: typeof SavedRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  RegisterEventIdRoute: typeof RegisterEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$eventId': {
      id: '/register/$eventId'
      path: '/register/$eventId'
      fullPath: '/register/$eventId'
      preLoaderRoute: typeof RegisterEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProfileRoute: ProfileRoute,
  RegistrationsRoute: RegistrationsRoute,
  SavedRoute: SavedRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  RegisterEventIdRoute: RegisterEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
